# Theme
source $ZDOTDIR/themes/frog.zsh-theme

# Alias
## Navigation
alias ..="cd .."
alias ...="cd ../.."
alias c=z

# Vim
alias vim=nvim

# ls remap
alias ls="eza --color=always --group-directories-first --icons"
alias ll="eza --color=always --group-directories-first -l --icons"
alias lla="eza --color=always --group-directories-first -la"
alias lt="eza --color=always --group-directories-first -aT"

